const data = [
    {
        id: 0,
        fav: false,
        name: 'Thai Veg Panang',
        timeToEat: "Lunch",
        cusine: "Thai",
        category: "Veg",
        image: "https://www.indianveggiedelight.com/wp-content/uploads/2021/05/panang-curry-featured.jpg",
        time: 50,
        quantityForServe: 3,
        nutrientInfo: 940,
        videoId: "NjZ8Uy558H0",
        ingrdients: [
            { item: "Dry Red Chilli", quantity: "10 no", image: "https://www.shutterstock.com/image-photo/dried-red-chili-peppers-isolated-260nw-360141881.jpg" },
            { item: "Garlic", quantity: "6 no", image: "https://thumbs.dreamstime.com/b/garlic-bulbs-market-stall-49430250.jpg" },
            { item: "Lemon Zest", quantity: "1 no", image: "https://static.onecms.io/wp-content/uploads/sites/19/2013/03/14/lemon-zest-hero-2000.jpg" },
            { item: "Soy Sauce", quantity: "2 tsp", image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Soy_sauce_2.jpg" },
            { item: "Carrot", quantity: "2 no", image: "https://static9.depositphotos.com/1642482/1148/i/950/depositphotos_11489080-stock-photo-fresh-carrots.jpg" },
            { item: "Bell Pepper", quantity: "1 no", image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Green-Yellow-Red-Pepper-2009.jpg" },
            { item: "Salt", quantity: "1 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
        ]
    },
    
    {
        id: 1,
        fav: false,
        name: 'Onion Bonda',
        timeToEat: "Evening Snaks",
        image: "https://img-global.cpcdn.com/recipes/9f9937894e1284a8/680x482cq70/onion-bondavengaya-bonda-recipe-main-photo.jpg",
        time: 25,
        category: "Veg",
        cusine: "South Indian",
        quantityForServe: 3,
        nutrientInfo: 273,
        videoId: "V7uqhYJfGsE",
        ingrdients: [
            { item: "Onion", quantity: "4 no", image: "https://www.shutterstock.com/image-photo/red-whole-sliced-onion-isolated-260nw-1684863088.jpg" },
            { item: "Salt", quantity: "1 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Green Chilli", quantity: "1 no", image: "https://t4.ftcdn.net/jpg/05/62/12/05/360_F_562120531_315RMvo2HEmcKHUxk3XekoVcF2g6t01t.jpg" },
            { item: "Maida", quantity: "2 cup", image: "https://www.shutterstock.com/image-photo/finely-milled-refined-wheat-flour-260nw-685703245.jpg" },
            { item: "Sun Flower Oil", quantity: "For deep fry", image: "https://thumbs.dreamstime.com/b/sunflower-oil-seeds-sunflower-oil-seeds-wooden-table-102706460.jpg" },
        ]
    },
    

    {
        id: 2,
        fav: false,
        name: 'Ragi Koozh',
        timeToEat: "Breakfast, Lunch",
        category: "Veg",
        image: "https://img-global.cpcdn.com/recipes/cddf6a2528fdb358/1200x630cq70/photo.jpg",
        time: 20,
        cusine: "South Indian",
        quantityForServe: 3,
        nutrientInfo: 74,
        videoId: "Nj-Tae47igA",
        ingrdients: [
            { item: "Ragi Flour", quantity: "5 tbsp", image: "https://www.shutterstock.com/image-photo/ragi-nachni-known-finger-millet-260nw-1101936836.jpg" },
            { item: "Water", quantity: "3 cup", image: "https://thumbs.dreamstime.com/b/glass-clean-drinking-water-44066082.jpg" },
            { item: "Sugar", quantity: "3 tsp", image: "https://www.shutterstock.com/image-photo/white-sugar-wooden-bowl-scoop-260nw-1046986462.jpg" },
            { item: "Salt", quantity: "1 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Milk", quantity: "1 cup", image: "https://images.healthshots.com/healthshots/en/uploads/2023/01/06161102/skimmed-milk.jpg" }
        ]
    },
    {
        id: 3,
        fav: false,
        timeToEat: "Lunch",
        name: 'Chicken Angara',
        image: "https://zaykarecipes.com/eng/wp-content/uploads/2020/05/Chicken-Angara-Recipe.jpg",
        time: 50,
        cusine: "North Indian",
        quantityForServe: 5,
        nutrientInfo: 449,
        videoId: "VA5j78BD5zM",
        category: "Non-veg",
        ingrdients: [
            { item: "Cloves", quantity: "5 no", image: "https://media.istockphoto.com/id/1053618050/photo/clove-in-a-wooden-spoon-on-old-table.jpg?b=1&s=170667a&w=0&k=20&c=rbr--24ICqrniX7EtBWkLC5agQ6g5SwQQliU6Pdy8zA=" },
            { item: "Green Cardamom", quantity: "6 no", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpg3ISRyG3kUCc2_NrVcj8SK8tcxYh8aG0Eg&usqp=CAU" },
            { item: "Black Peppercorns", quantity: "1 tsp", image: "https://media.istockphoto.com/id/469858939/photo/black-pepper.jpg?s=612x612&w=0&k=20&c=GwF_EvFrYNtwTdY5DN9gRS1eJnRf949jUQeqgqoLExE=" },
            { item: "Salt", quantity: "2 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Ghee", quantity: "2 tsp", image: "https://thumbs.dreamstime.com/b/ghee-clarified-butter-close-up-wooden-bowl-silver-spoon-selective-focus-indian-desi-ghee-pure-ghee-served-101142931.jpg" },
            { item: "Chicken Meat", quantity: "1 kg", image: "https://www.shutterstock.com/image-photo/raw-chicken-meat-on-wooden-260nw-759192829.jpg" },
            { item: "Curd", quantity: "1 cup", image: "https://static.india.com/wp-content/uploads/2021/06/MicrosoftTeams-image-9.jpg" },
            { item: "Almonds", quantity: "2 tsp", image: "https://www.shutterstock.com/image-photo/almond-raw-piece-full-macro-260nw-2033102012.jpg" },
        ]
    },
    {
        id: 4,
        fav: false,
        name: 'Poori',
        timeToEat: "Breakfast, Dinner",
        image: "https://img.freepik.com/premium-photo/poori-masala-curry-aloo-sabzi-puri_466689-77508.jpg",
        time: 35,
        cusine: "South Indian",
        category: "Veg",
        quantityForServe: 10,
        nutrientInfo: 135,
        videoId: "t1_jX2reT-M",
        ingrdients: [
            { item: "Wheat Flour", quantity: "2 cup", image: "https://thumbs.dreamstime.com/b/wheat-grain-flour-22804776.jpg" },
            { item: "Salt", quantity: "1 cup", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Rava", quantity: "2 tbsp", image: "https://www.shutterstock.com/image-photo/raw-semolina-flour-rava-powder-260nw-1132324025.jpg" },
            { item: "Sun Flower Oil", quantity: "1 tps", image: "https://thumbs.dreamstime.com/b/sunflower-oil-seeds-sunflower-oil-seeds-wooden-table-102706460.jpg" },
        ]
    },
    {
        id: 5,
        fav: false,
        name: 'Naan',
        timeToEat: "Lunch, Dinner",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/butter-naan.jpg",
        time: 40,
        cusine: "North Indian",
        category: "Veg",
        videoId: "qnzBkCkv9gs",
        quantityForServe: 4,
        nutrientInfo: 286,
        ingrdients: [
            { item: "Maida", quantity: "2 cup", image: "https://www.shutterstock.com/image-photo/finely-milled-refined-wheat-flour-260nw-685703245.jpg" },
            { item: "Salt", quantity: "1 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Sugar", quantity: "1 tbsp", image: "https://www.shutterstock.com/image-photo/white-sugar-wooden-bowl-scoop-260nw-1046986462.jpg" },
            { item: "Baking Powder", quantity: "1 pinch", image: "https://lacasa.co.in/wp-content/uploads/2021/09/baking-soda-powder.jpeg" },
            { item: "Sun Flower Oil", quantity: "1 tbsp", image: "https://thumbs.dreamstime.com/b/sunflower-oil-seeds-sunflower-oil-seeds-wooden-table-102706460.jpg" },
            { item: "Milk", quantity: "1 cup", image: "https://images.healthshots.com/healthshots/en/uploads/2023/01/06161102/skimmed-milk.jpg" },
        ]
    },
    {
        id: 6,
        fav: false,
        timeToEat: "Dinner",
        name: 'Paneer Teriyaki',
        image: "https://www.onedishwonder.in/data/products/paneer-teriyaki-(couple)/1654009501paneer_teriyaki.jpg",
        time: 35,
        cusine: "Japanese",
        quantityForServe: 4,
        nutrientInfo: 595,
        videoId: "SMeUXhhxQC8",
        category: "Veg",
        ingrdients: [
            { item: "Honey", quantity: "2 tbsb", image: "https://thumbs.dreamstime.com/b/fresh-honey-8994238.jpg" },
            { item: "Green Cardamom", quantity: "6 no", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpg3ISRyG3kUCc2_NrVcj8SK8tcxYh8aG0Eg&usqp=CAU" },
            { item: "Black Peppercorns", quantity: "1 tsp", image: "https://media.istockphoto.com/id/469858939/photo/black-pepper.jpg?s=612x612&w=0&k=20&c=GwF_EvFrYNtwTdY5DN9gRS1eJnRf949jUQeqgqoLExE=" },
            { item: "Salt", quantity: "2 tsp", image: "https://thumbs.dreamstime.com/b/crystals-shallow-salt-scoop-spoon-dark-gray-table-background-advertising-salty-salted-food-128319623.jpg" },
            { item: "Ghee", quantity: "2 tsp", image: "https://thumbs.dreamstime.com/b/ghee-clarified-butter-close-up-wooden-bowl-silver-spoon-selective-focus-indian-desi-ghee-pure-ghee-served-101142931.jpg" },
            { item: "Paneer", quantity: "400 grams", image: "https://static.toiimg.com/photo/93877316.cms" },
            { item: "Curd", quantity: "1 cup", image: "https://static.india.com/wp-content/uploads/2021/06/MicrosoftTeams-image-9.jpg" },
            { item: "Almonds", quantity: "2 tsp", image: "https://www.shutterstock.com/image-photo/almond-raw-piece-full-macro-260nw-2033102012.jpg" },
        ]
    },
]

export default data